import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Shared/Sidebar";
import MobileMenu from "@/components/Shared/MobileMenu";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-dvh`}>
        <div className="lg:flex w-full max-w-[1440px] mx-auto">
          <Sidebar />
          <MobileMenu />
          <main className="w-full flex-shrink">{children}</main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
